Program type constant updated. Only shows for grantee reports
adhocteam/Head-Start-TTADP pull request #153
Opened 2021-02-05 22:38 UTC by jasalisbury

**Description of change**

Program type constant updated to the values defined in the linked ticket. Program type field only shows when the report is for grantees, it is hidden for non-grantees.

**How to test**

1) Pull down
2) Start a report, select `grantee` and note `Program type(s)` is shown
3) Select `non-grantee` and note `Program type(s)` is hidden

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/170

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [x] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-02-08 20:12 UTC, dcmcand commented
Program types still shows up on the review page if you select nongrantee (with no value). Is that correct?

Also, would it be better to have it show up when you select grantee rather than go away when you select nongrantee? Currently, you can select a program type then select nongrantee. Your selection isn't saved or anything, I just wonder if it might be confusing.

2021-02-08 21:43 UTC, jasalisbury commented
> Program types still shows up on the review page if you select nongrantee (with no value). Is that correct?

I don't see a good way of hiding it right now, something to keep in mind when we refactor the review accordions to support the download links

> Also, would it be better to have it show up when you select grantee rather than go away when you select nongrantee? Currently, you can select a program type then select nongrantee. Your selection isn't saved or anything, I just wonder if it might be confusing.

Good catch, I'll make it hidden until the user selects `grantee`

2021-02-08 22:11 UTC, dcmcand approved these changes
Very nice.

2021-02-09 19:39 UTC, gopar approved these changes

2021-02-10 15:14 UTC, rahearn requested changes
Good stuff, just the one cleanup task on the test name.

2021-02-10 15:14 UTC, rahearn commented on frontend/src/pages/ActivityReport/__tests__/index.js
> +  it('hides program type if non-grantee is selected', async () => {
Can we switch the description to match the behavior now - hidden until shown if grantee is selected.

2021-02-10 15:37 UTC, rahearn approved these changes
🚢

2021-02-10 17:27 UTC, merged