Add reset script
adhocteam/Head-Start-TTADP pull request #158
Opened 2021-02-09 20:13 UTC by dcmcand

**Description of change**
Adds a small convenience script i use when changing branches.

This script: 
1. stops all running containers
2. deletes current docker volumes
3. reinstalls deps
4. runs migrations
5. runs seeders
It makes sure you have a clean environment when switching branches.

**Caution**
This script removes all docker volumes not attached to a running container. If you have other docker volumes that you are not ok with deleting, do not run this script.

**How to test**
run `yarn docker:reset`

2021-02-09 20:16 UTC, jasalisbury reviewed
Looks good, but some pre-signed url stuff got in as well. Will either want to update this PR or wait for the pre-signed stuff to make it to main.

2021-02-09 20:44 UTC, dcmcand commented
Removed the presigned url stuff.

2021-02-09 20:44 UTC, jasalisbury approved these changes

2021-02-09 22:44 UTC, rahearn requested changes
Let's make the change to `down` so we don't accidentally hose a future developer's volumes.

2021-02-09 22:44 UTC, rahearn commented on bin/reset-all
> +docker volume prune
These two could be combined as `yarn docker:stop --volumes` which would also have the benefit on not removing unrelated volumes.

2021-02-10 14:52 UTC, rahearn approved these changes

2021-02-10 16:21 UTC, merged