Add the context menu component
adhocteam/Head-Start-TTADP pull request #171
Opened 2021-02-15 22:07 UTC by jasalisbury

**Description of change**
 * Context menu is a clickable ellipsis
 * When not open only the ellipsis is shown
 * When open a menu of actions is shown
 * If a user clicks the action in the menu the corresponding aciton is called
 * The menu closes 'onBlur'

**How to test**
Verify tests pass

**Screenshots**

![Screenshot from 2021-02-15 15-39-45](https://user-images.githubusercontent.com/6631790/107997140-b0b7f700-6fa7-11eb-8a56-994c2a073b1c.png)
---
![Screenshot from 2021-02-15 15-39-57](https://user-images.githubusercontent.com/6631790/107997137-b01f6080-6fa7-11eb-9efc-1e1ae3c19419.png)

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/296

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-02-15 22:38 UTC, gopar approved these changes
Awesome! I was totally doing the wrong thing when trying to build it.

2021-02-17 14:28 UTC, rahearn reviewed
Do you have a quick gist or code sample for where I can plug the `<ContextMenu>` in to manually test it out?

2021-02-17 14:28 UTC, rahearn commented on frontend/src/components/ContextMenu.js
> +        aria-label={label}
Good use of the `aria-label` but I think for accessibility there's likely some more we need to do. [`aria-haspopup`](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20161214/examples/menu-button/menu-button-1/menu-button-1.html) might be a good thing to look at

2021-02-17 14:30 UTC, rahearn commented on frontend/src/components/ContextMenu.js
> +        aria-label={label}
Here's probably a better link for `aria-haspopup` https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup

2021-02-17 21:03 UTC, rahearn requested changes
One more accessibility issue. When using VoiceOver, it announces that the popup menu can be closed with `Escape` but that doesn't work.

Beyond that, there were some styling issues (and usage issues, since the button's active region didn't perfectly line up with the visual region, leading to activated clicks when I thought I'd be closing the menu) when I tried to attach the context menu to the activity reports list. I'm ok with not addressing those until this component is in use in those places, but I wanted to note that they'd be something to watch out for.

2021-02-17 21:36 UTC, jasalisbury commented
> Do you have a quick gist or code sample for where I can plug the `<ContextMenu>` in to manually test it out?

@rahearn I could have sworn I sent an example on how to use the `<ContextMenu>` but I can't find it anywhere... Did I actually send you an example somewhere?

2021-02-17 21:41 UTC, rahearn commented
> Did I actually send you an example somewhere?

No, but that's ok, it's not the most complicated component to wire up. I used it this way:

```
diff --git a/frontend/src/pages/Landing/index.js b/frontend/src/pages/Landing/index.js
index 3152da2..c1fbed5 100644
--- a/frontend/src/pages/Landing/index.js
+++ b/frontend/src/pages/Landing/index.js
@@ -132,9 +132,7 @@ function renderReports(reports) {
           </Tag>
         </td>
         <td>
-          <button type="button" className="smart-hub--dotdotdot">
-            ...
-          </button>
+          <ContextMenu label="options" menuItems={[{label: "Edit", onClick: () => { console.log("Edit")}}, {label: "Delete", onClick: () => { console.log("Delete") }}]} />
         </td>
       </tr>
     );
```

2021-02-17 21:47 UTC, jasalisbury commented
> Beyond that, there were some styling issues (and usage issues, since the button's active region didn't perfectly line up with the visual region, leading to activated clicks when I thought I'd be closing the menu) when I tried to attach the context menu to the activity reports list. I'm ok with not addressing those until this component is in use in those places, but I wanted to note that they'd be something to watch out for.

Are you talking about the buttons being the full width of the menu? If so that was intentional, but as you say we can address it when the component is in use.

2021-02-18 01:53 UTC, rahearn commented
> Are you talking about the buttons being the full width of the menu?

This is what I'm seeing on Chrome with the context menu on the activity reports table. The focus outline is where I can click on the button, but you can see it doesn't extend to the visual left, and it's beyond the visual right. Maybe a bad interaction with the `SimpleBar` components?

<img width="237" alt="Screen Shot 2021-02-17 at 8 49 21 PM" src="https://user-images.githubusercontent.com/285842/108292257-bf4a0e00-7161-11eb-81fe-b71d069d41a6.png">

2021-02-18 01:53 UTC, rahearn approved these changes

2021-02-18 02:07 UTC, jasalisbury commented
> > Are you talking about the buttons being the full width of the menu?
> 
> This is what I'm seeing on Chrome with the context menu on the activity reports table. The focus outline is where I can click on the button, but you can see it doesn't extend to the visual left, and it's beyond the visual right. Maybe a bad interaction with the `SimpleBar` components?
> 
> <img alt="Screen Shot 2021-02-17 at 8 49 21 PM" width="237" src="https://user-images.githubusercontent.com/285842/108292257-bf4a0e00-7161-11eb-81fe-b71d069d41a6.png">

Oh yeah I don't see that where I put it, we'll probably have to mess with the styles when it gets placed in the table.

2021-02-18 02:07 UTC, merged