Add additional buttons at bottom of activity report
adhocteam/Head-Start-TTADP pull request #178
Opened 2021-02-17 21:30 UTC by jasalisbury

**Description of change**
 * Split up saving of the report to the API and navigation
 * No longer save to API when navigating pages (still save after 2 minutes)
 * Add "save draft" button that saves to API
 * Continue renamed "Save & Continue"
 * Can save draft from the submitter draft review page

**How to test**
1) Pull down
2) Use the new buttons in an activity report (make sure to have at least one recipient). Data only hits the API when "Save & Continue", "Save draft" are pressed and when the 2 minute auto-save triggers.

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/0

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-02-18 18:49 UTC, dcmcand approved these changes
Works well.

2021-02-18 20:37 UTC, gopar approved these changes

2021-02-22 20:08 UTC, rahearn requested changes
Looks good, except I think I'm hitting a bug with creating a new report with the "Save Draft" button.

Expected:
1) select grantee & choose a grantee
2) click "save draft"
3) see a save success message under the sidenav
4) see that the url has updated from `new` to the new report's ID

Actual:
1&2 are the same, I see the POST api call in dev tools, I never see 3 or 4 in the UI.

2021-02-22 21:15 UTC, rahearn approved these changes

2021-02-22 21:23 UTC, merged