Refactor activity report review pages
adhocteam/Head-Start-TTADP pull request #185
Opened 2021-02-18 21:21 UTC by jasalisbury

**Description of change**
 * Each page has more control over what shows up on it's review page
 * Topics and resources shows download links to the files that have been uploaded to the report

**How to test**

1) Pull down, fill out a report
2) Add files to the report
3) Look at the files on the review page. You may have to invert the logic in `frontend/src/pages/ActivityReport/Pages/Review/FileReviewItem.js` line 16 in order to see an actual download link (unless https://github.com/adhocteam/Head-Start-TTADP/pull/176 is merged). We only show the download link for approved files and files are never currently approved.

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/247

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-02-24 15:05 UTC, dcmcand approved these changes
Looks good. This should make customizing the review page much easier!

2021-03-01 20:29 UTC, rahearn requested changes
There's an issue where if you upload a file, click save and continue, and then jump right to the review page you trigger a pretty fatal error:

<img width="1048" alt="Screen Shot 2021-03-01 at 3 28 12 PM" src="https://user-images.githubusercontent.com/285842/109554934-eaf2bf80-7aa2-11eb-9344-bf973e286114.png">

2021-03-01 21:38 UTC, jasalisbury commented
@dcmcand requested a re-review because I made a few file upload changes in my latest commit you might want to checkout.

2021-03-02 19:43 UTC, dcmcand reviewed
The file stuff looks good. I like returning a url right away. There is something funky with printing though. It looks like only the first file shows up when you print.

2021-03-02 19:45 UTC, dcmcand requested changes
There is something funky with printing though. It looks like only the first file shows up when you print.

2021-03-02 23:31 UTC, jasalisbury commented
> There is something funky with printing though. It looks like only the first file shows up when you print.

Can you be more specific on how you were able to only see a single file? I was able to see two files here:
![Screenshot from 2021-03-02 17-31-03](https://user-images.githubusercontent.com/6631790/109729201-22359f00-7b7d-11eb-9f66-fd543bae8630.png)

2021-03-03 14:17 UTC, dcmcand commented
I also tried it  with a completed report. As you can see, I had four files attached.
![Screenshot from 2021-03-03 09-16-27](https://user-images.githubusercontent.com/6248903/109818689-2b7d4500-7c2b-11eb-9f88-3e6edccc1afa.png)
If you look at the attached report, only one resource and no attachments show up.
[Review and submit - Activity Report - TTA Smart Hub.pdf](https://github.com/adhocteam/Head-Start-TTADP/files/6076536/Review.and.submit.-.Activity.Report.-.TTA.Smart.Hub.pdf)

2021-03-03 15:55 UTC, jasalisbury commented
@dcmcand Print should be working correctly now

2021-03-03 16:07 UTC, dcmcand approved these changes
Nice!

2021-03-03 22:01 UTC, rahearn commented on docker-compose.yml
> +    command: ["--endpoint-url", "http://minio:9000", "s3api", "create-bucket", "--bucket", "$S3_BUCKET"]
Sorry for tagging along on your PR, @jasalisbury. I found this while reviewing this PR, but the change it totally unrelated to your changes.

2021-03-03 22:25 UTC, rahearn approved these changes
🎉

2021-03-04 15:56 UTC, merged