Request Permissions view & HTTPError handler
adhocteam/Head-Start-TTADP pull request #208
Opened 2021-03-03 23:21 UTC by dcloud

**Description of change**

Users who have an account but are denied access because they have no permissions should see a message helping them request permission. On the backend, `authMiddleware` will return a '403: Forbidden' http response, so the frontend should understand this as a permissions issue (different from a '401: Unauthorized').

This PR adds an `HTTPError` custom class, which is used by the frontend to handle HTTP error codes. The `App.js` will set `authError` if an HTTP 403 error is thrown when fetching a user.

**How to test**

Set `CURRENT_USER_ID=2` in your .env file: Dumbledore is a user with no permissions.

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/139

**Checklist**

- [ ] Meets issue criteria
- [ ] Code tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-03-04 22:33 UTC, gopar approved these changes
LGTM
Also had no idea you could do 
```
export {
  xxx as yyy,
  anotherThingy
}
```
Learn something new \o/

2021-03-05 19:45 UTC, jasalisbury approved these changes
:tada:

2021-03-08 15:47 UTC, rahearn requested changes
Everything here looks great, but can we remove the request permissions section from the unauthenticated dialog?

<img width="560" alt="Screen Shot 2021-03-08 at 10 46 28 AM" src="https://user-images.githubusercontent.com/285842/110344588-a4014e80-7ffb-11eb-83b2-49595b04c386.png">

I want to prevent, as much as possible, anyone filling out that form before they login the first time with HSES, since I can't assign permissions if they haven't created the User model by signing in.

2021-03-08 15:47 UTC, rahearn commented on frontend/src/permissions.js
> +};
I love consolidating these here, and I didn't know that you could specify `default` as part of `export { xxx as yyy }`. Neat trick

2021-03-08 15:47 UTC, rahearn commented on frontend/src/__tests__/App.js
> +    it('displays the "request permissions" page', async () => {
Hooray for finding and updating the placeholder test.

2021-03-08 19:28 UTC, dcloud commented
> Everything here looks great, but can we remove the request permissions section from the unauthenticated dialog?
> 

Removed via 9e6b293d1de344e33abb4aae341de90b73035b56

2021-03-08 19:34 UTC, rahearn approved these changes

2021-03-08 19:49 UTC, merged