Cm 302 create mainenance page
adhocteam/Head-Start-TTADP pull request #218
Opened 2021-03-08 21:22 UTC by dcmcand

**Description of change**
Add maintenance page

**How to test**

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/302

**Checklist**

- [ ] Meets issue criteria
- [ ] Code tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-03-08 21:41 UTC, rahearn commented on manifest.yml
> +    force_https: "true"
I don't think we'd need `force_https` (unless that's explicitly in the cloud.gov docs) and I think you should specify the memory quota for this app. I think 512M is the default and I can't imagine the `staticfile_buildpack` would need that.

2021-03-09 15:51 UTC, kryswisnaskas approved these changes
Looks good!

The header style differs a little bit from the main application. We might want to adjust it at some point, but this is a lower priority.

2021-03-09 18:05 UTC, rahearn requested changes
Looks good - just swap out that one span for an h1 and ensure the double require goes away.

2021-03-09 18:05 UTC, rahearn commented on maintenance_page/index.html
> +            <span>The TTA Smart Hub is temporarily down.</span>
The page is missing a `h1` header. I think this span is the best option to use.

2021-03-09 18:05 UTC, rahearn commented on src/worker.js
> +require('newrelic');
The weird double require is showing up here, just make sure it goes away in the next merge of main.

2021-03-09 19:14 UTC, rahearn approved these changes

2021-03-09 19:16 UTC, merged