Import Activity Reports from smartsheets
adhocteam/Head-Start-TTADP pull request #224
Opened 2021-03-10 23:31 UTC by dcloud

**Description of change**

**How to test**

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/0

**Checklist**

- [ ] Meets issue criteria
- [ ] Code tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-03-11 19:27 UTC, dcloud commented on src/services/activityReports.js
> +    attributes: { exclude: ['imported', 'legacyId'] },
I may need to undo that if we're going to make a frontend view of the un-processed imported data.

2021-03-11 20:49 UTC, rahearn commented
Talking about this with @dcloud. We decided on the following:

Things we need right away:

* a legacy view-only mode that displays data from of the import json
* Matching grant numbers in the imported data to existing grants. If none found, continue to leave blank

Things we need to do soon, but post-mvp

* create a job to match user emails (owners, collaborators, and approving mangers) in the import json to newly created user emails in the User table
* Ryan to import comments and attachments from smartsheet into the hub

As users start to login in the first week, old ARs will be missing attachments, and user relationships will be filled in as users register.
There may be other mismatches between valid form values in Smartsheet vs Smart Hub, we will reconcile those as best as possible through later enhancements.

2021-03-12 21:22 UTC, dcloud commented
Putting this in "ready for review" status. The import script is missing a test.js file, but I'll need some time to generate a testable CSV. Otherwise, I think the tires are ready for kicking, and thanks to @jasalisbury there is a custom legacy report view/route so you can look at things on the frontend.

2021-03-12 23:16 UTC, rahearn requested changes

2021-03-12 23:19 UTC, jasalisbury commented on frontend/src/fetchers/activityReports.js
> +  const res = await get(join(activityReportUrl, 'legacy', legacyId.toString(DECIMAL_BASE)));
Yeah good catch

2021-03-12 23:24 UTC, dcloud commented
I'll note that this is essentially done. The test I added for the import command is fairly minimal, and could be expanded on. However, tests in other files were failing for me locally, so I'd like to have CircleCI (and other reviewers, possibly) verify that the new tests aren't breaking others (since they do create AR database records).

2021-03-12 23:25 UTC, dcloud commented on .gitignore
> +.tmp
Addressed via 0d76df0

2021-03-13 00:35 UTC, rahearn approved these changes
Really impressed with the import and display code here. Great work

2021-03-13 00:35 UTC, rahearn commented on src/tools/importActivityReports.test.js
> +      expect.objectContaining({ id: expect.anything(), legacyId: 'R14-AR-001132', requester: 'Grantee' }),
Ooh, I like these matchers. That's great.

2021-03-15 14:28 UTC, kryswisnaskas commented
Looks good! Verified I was able to import all regions and view the individual reports under the legacy endpoint.

The only issue I saw was the display of "Status" in some of the reports. Suggested change to the Landing/index.css

```
.smart-hub--status- {
  display: none;
}

.smart-hub--status-null {
  display: none;
}
```
While this might not be the most elegant solution, it appears to be the simplest.

2021-03-15 15:08 UTC, jasalisbury commented
> Looks good! Verified I was able to import all regions and view the individual reports under the legacy endpoint.
> 
> The only issue I saw was the display of "Status" in some of the reports. Suggested change to the Landing/index.css
> 
> ```
> .smart-hub--status- {
>   display: none;
> }
> 
> .smart-hub--status-null {
>   display: none;
> }
> ```
> 
> While this might not be the most elegant solution, it appears to be the simplest.

After looking a bit at this I realized we only show reports that are approved in the main reports table. This means imported reports that are not approved will not show up in either reports table. A user will have to know the legacy ID to view a legacy report that has not been approved.

2021-03-15 15:10 UTC, rahearn commented
> A user will have to know the legacy ID to view a legacy report that has not been approved.

Yes, for now.

> Things we need to do soon, but post-mvp
> create a job to match user emails (owners, collaborators, and approving mangers) in the import json to newly created user emails in the User table

Once this is done non-approved reports will start appearing in the appropriate user alert tables

2021-03-15 15:52 UTC, kryswisnaskas approved these changes

2021-03-15 17:20 UTC, merged