small fixes
adhocteam/Head-Start-TTADP pull request #248
Opened 2021-03-16 18:15 UTC by jasalisbury

**Description of change**
 * Report table context menu for approved reports changed from "edit" to "view"
 * Error message state lifted up to the activity report
 * Not editable alert for submitted reports duplicated below "reset to draft" button
 * Accordion items auto expanded for non-draft/needs action reports
 * Resources used is now a `textarea`
 * Title and other verbiage tweaked for next steps
 * Report status tag capitalized and green if report is approved

**How to test**
Pull down or visit [sandbox](https://tta-smarthub-sandbox.app.cloud.gov/)

**Issue(s)**
* https://github.com/HHS/Head-Start-TTADP/issues/392

**Checklist**

- [x] Meets issue criteria
- [x] Code tested
- [x] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-03-16 19:52 UTC, dcmcand reviewed
Is this correct? Both say "What have you agreed to do next?"

![Screenshot from 2021-03-16 15-46-48](https://user-images.githubusercontent.com/6248903/111371258-14aa0a00-8691-11eb-88b5-a917de55ed05.png)

2021-03-16 20:00 UTC, jasalisbury commented
> Is this correct? Both say "What have you agreed to do next?"
> 
> ![Screenshot from 2021-03-16 15-46-48](https://user-images.githubusercontent.com/6248903/111371258-14aa0a00-8691-11eb-88b5-a917de55ed05.png)

Yeah it isn't correct, I read the issue wrong, working on an update.

2021-03-16 20:22 UTC, dcmcand approved these changes
:tada:

2021-03-16 20:25 UTC, rahearn commented
> * Report table context menu for approved reports changed from "edit" to "view"

Is this duplicative of #250?

2021-03-16 20:26 UTC, jasalisbury commented
> > * Report table context menu for approved reports changed from "edit" to "view"
> 
> Is this duplicative of #250?

Yeah but that PR fixes legacy links and has some style changes. We can either merge that one through to main or into this branch

2021-03-16 20:29 UTC, rahearn commented
> We can either merge that one through to main or into this branch

Looks like they both had the same frontend failure too, why don't you merge #250 into this one and I'll review them together.

2021-03-17 13:42 UTC, rahearn requested changes
Looks good, save the one styling fix.

While you're at it, I have one other tweak that I think should be easy but wasn't in the original ticket. Can you hide the "Edit" links on the review page for reports that aren't editable? I think it should be the same logic as deciding whether to expand the accordion or not.

2021-03-17 13:42 UTC, rahearn commented on frontend/src/pages/Landing/index.css
> +  max-width: 20px;
I think this is causing the button to look weird:

<img width="91" alt="Screen Shot 2021-03-17 at 9 32 45 AM" src="https://user-images.githubusercontent.com/285842/111476199-5031ec00-8704-11eb-9529-3e529edb7a94.png">

2021-03-17 13:43 UTC, rahearn commented
> Can you hide the "Edit" links on the review page for reports that aren't editable?

If this is more than a one line fix then please open a new JIRA ticket for it and let me know.

2021-03-17 14:28 UTC, jasalisbury commented
> > Can you hide the "Edit" links on the review page for reports that aren't editable?
> 
> If this is more than a one line fix then please open a new JIRA ticket for it and let me know.

It's more than a one line fix, I'll create a ticket in JIRA

2021-03-17 14:41 UTC, rahearn approved these changes
🎉

2021-03-17 14:45 UTC, merged