Add ability to delete a report in My Alerts
adhocteam/Head-Start-TTADP pull request #267
Opened 2021-04-01 22:07 UTC by gopar

**Description of change**
In the My Alerts section, theres a new column for the context menu which allows the user to view the report or delete it.

** NOTE**: Delete ability is not done in the backend, once that is done, the delete functionality will work.

**How to test**
Pull down changes and run locally.
Go to My Alerts and you should see the new context menu.

**Issue(s)**
* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-83

**Checklist**

- [x] Meets issue criteria
- [ ] Code tested
- [ ] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [ ] Documentation updated
    - API methods
    - Boundary and Data Flow Diagrams
    - [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions with the [Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md)
    - OSCAL templates completed when security controls are implemented or modified

2021-04-09 14:10 UTC, kryswisnaskas commented
This looks pretty good at a first glance. I am still reviewing - so far found that the modal can show up underneath the main table. I thought you might want to see this:

![image](https://user-images.githubusercontent.com/28231976/114192719-d0222f00-991b-11eb-8896-2bc9926cdffa.png)

2021-04-14 19:13 UTC, dcloud reviewed
I took a look at this after reviewing the backend PR. That DeleteReportModal is looking pretty good so far. 

I did see the modal appear under the table, which seems like some `z-index` issues. Which reminded me that I saw similar issues when working on TTAHUB-89 – the ContextMenu was being cut off if it was the menu for the last row in a table. I see the ContextMenu being cut off here (again only the last row is affected). I _think_ the SimpleBar that wraps these tables introduces some z-index weirdness.

2021-04-14 20:41 UTC, gopar commented on frontend/src/pages/Landing/index.js
> -          <ContextMenu label={contextMenuLabel} menuItems={menuItems} />
yeah I was just fixing those. Looks like its in there to keep. I'll make the chanes in my branch

2021-04-14 20:43 UTC, gopar commented on frontend/src/pages/NotFound/__tests__/index.js
> +import '@testing-library/jest-dom';
You got me :p 
Also it was to make it not appear anymore in the low coverage part of the report. This didn't really bump the coverage

2021-04-19 15:24 UTC, jasalisbury reviewed
Looks good! Do we want to hide the delete option behind a feature flag until the backend is finished?

2021-04-19 15:24 UTC, jasalisbury commented on frontend/src/pages/Landing/MyAlerts.js
> +        label: 'Open report',
The table below labels this as `View`, will want to update them to match (can probably also drop `report` on both labels)

2021-04-19 15:24 UTC, jasalisbury commented on frontend/src/components/__tests__/DeleteReportModal.js
> +  it('exists when escapse key is pressed', async () => {
```suggestion
  it('exits when escapse key is pressed', async () => {
```

2021-04-19 15:31 UTC, gopar commented on frontend/src/Constants.js
> +  DELETED: 'deleted',
Was included in previous backend PR but for some reason it wasn't merged into the codebase? /shrug

2021-04-19 17:34 UTC, gopar commented on frontend/src/pages/Landing/MyAlerts.js
> +      fetchReports();
For some reason refetchting the reports isn't working, you have to manually refresh to see the report no longer there. Looking into it.

2021-04-20 14:07 UTC, kryswisnaskas commented
Looks good. Could we match the delete confirmation box closer to:
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/137498615/simulate/no-panels ?

2021-04-20 19:57 UTC, gopar commented on frontend/src/pages/Landing/MyAlerts.js
> +      fetchReports();
Looks like the DB isn't being updated fast enough for when the a new query is being searched for? They data that is returned when re-fetching the db gives a status of DRAFT for the deleted report, but when checking the db manually after, it's status is set to DELETED. Deployed to staging to check if this happens in deployment. Looks like accounts have been reset in staging tho

2021-04-22 17:45 UTC, kryswisnaskas commented
The delete works now and updates the list of alerts! 👍 

The only outstanding item is the "different than design" look of the modal. Other than that it should be good to go.
(https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/137498615/simulate/no-panels)

2021-04-29 15:06 UTC, rahearn commented
What's the status of this? Ready for me to take a look at? (If it is, please also bring it up to date with main before I do)

2021-05-07 16:37 UTC, kryswisnaskas approved these changes

2021-05-10 14:10 UTC, rahearn requested changes
delete functionality works well, and looks good for the most part. We just need to implement the fix from #293 on the alerts table

<img width="214" alt="Screen Shot 2021-05-10 at 9 48 25 AM" src="https://user-images.githubusercontent.com/285842/117672500-e79d4380-b177-11eb-902b-06a3eaeca6a8.png">

2021-05-10 15:28 UTC, rahearn approved these changes

2021-05-10 16:54 UTC, merged