Ttahub 174/update list of topics
adhocteam/Head-Start-TTADP pull request #353
Opened 2021-07-08 17:45 UTC by thewatermethod

## Description of change
- Update topic names in the front end javascript constants in which they live
- Write a recurring job to execute a sequelize update function to rename the offending topics
- Added unit test for job

## How to test
Create a new activity report, go to the topics and resources pane

Confirm that the topics are in alphabetical order and that:
- "CLASS: Classroom Organization" 
- "Behavioral/Mental Health / Trauma"
- "Curriculum (Instructional or Parenting)"
- "Environmental Health and Safety / EPRR"
- "Quality Improvement Plan/QIP"

appear.

To test recurring job aside from unit test, you'll need to run the updateTopicNames function and have some of the un-renamed topics in the database. As an example, to run it locally for me, I added it to an API handler so it would run arbitrarily, and ran SQL statements to confirm that the topics had been renamed.

## Issue(s)

* https://ocio-jira.acf.hhs.gov/browse/TTAHUB-174

## Checklists

### Every PR

- [x] Meets issue criteria
- [x] JIRA ticket status updated
- [x] Code is meaningfully tested
- [n/a] Meets accessibility standards (WCAG 2.1 Levels A, AA)
- [n/a] API Documentation updated
- [n/a] Boundary diagram updated
- [n/a] Logical Data Model updated
- [n/a] [Architectural Decision Records](https://adr.github.io/) written for major infrastructure decisions

### Production Deploy

- [ ] Staging smoke test completed

### After merge/deploy

- [ ] Update JIRA ticket status

2021-07-08 18:52 UTC, AdamAdHocTeam approved these changes
Looks good.

2021-07-08 19:55 UTC, kryswisnaskas commented
Looks very good! I verified that the update job worked. Nice! 
Only a minor comment.

2021-07-08 19:56 UTC, kryswisnaskas requested changes

2021-07-08 19:56 UTC, kryswisnaskas commented on src/lib/updateTopicNames.js
> +        console.log(`Renaming ${topic.old} to ${topic.renamed} in ${report.id}`);
Any reason not to use` logger.info` instead of `console.log `?

2021-07-09 12:40 UTC, kryswisnaskas approved these changes
🚀

2021-07-09 14:38 UTC, merged